version: "3.9"

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: codejr
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    environment:
      DB_URL: ${DB_URL}        
      PORT: ${PORT}            
      JWT_SECRET: ${JWT_SECRET} 
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mysql

volumes:
  mysql-data: